# Generated by Django 5.2.7 on 2025-10-17 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenBaiThi', models.CharField(max_length=200)),
                ('cachChamDiem', models.IntegerField()),
                ('phuongThucCham', models.CharField(choices=[('TIME', 'Chấm theo thời gian'), ('TEMPLATE', 'Chấm theo mẫu'), ('POINTS', 'Chấm theo thang điểm')], default='POINTS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CuocThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10, unique=True)),
                ('tenCuocThi', models.CharField(max_length=200)),
                ('trangThai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiamKhao',
            fields=[
                ('maNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaiThiTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='core.baithi')),
            ],
            options={
                'ordering': ['baiThi_id', 'stt'],
            },
        ),
        migrations.CreateModel(
            name='BaiThiTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('content', models.CharField(max_length=500)),
                ('max_score', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.baithitemplatesection')),
            ],
            options={
                'ordering': ['section_id', 'stt'],
            },
        ),
        migrations.CreateModel(
            name='BaiThiTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('score', models.IntegerField()),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='core.baithi')),
            ],
            options={
                'ordering': ['start_seconds', 'end_seconds', 'score'],
            },
        ),
        migrations.CreateModel(
            name='ThiSinh',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maNV', models.CharField(db_index=True, max_length=20)),
                ('hoTen', models.CharField(max_length=100)),
                ('chiNhanh', models.CharField(max_length=100)),
                ('vung', models.CharField(blank=True, max_length=100, null=True)),
                ('donVi', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nhom', models.CharField(max_length=50)),
                ('maCuocThi', models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True)),
                ('cuocThi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thi_sinh', to='core.cuocthi')),
            ],
        ),
        migrations.CreateModel(
            name='VongThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenVongThi', models.CharField(max_length=200)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vong_thi', to='core.cuocthi')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuChamDiem',
            fields=[
                ('maPhieu', models.AutoField(primary_key=True, serialize=False)),
                ('maCuocThi', models.CharField(db_index=True, editable=False, max_length=10)),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baithi')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuocthi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giamkhao')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thisinh')),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vongthi')),
            ],
        ),
        migrations.AddField(
            model_name='baithi',
            name='vongThi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_thi', to='core.vongthi'),
        ),
        migrations.AddConstraint(
            model_name='thisinh',
            constraint=models.UniqueConstraint(fields=('maNV', 'cuocThi'), name='uniq_thisinh_maNV_ct'),
        ),
        migrations.AlterUniqueTogether(
            name='phieuchamdiem',
            unique_together={('thiSinh', 'giamKhao', 'baiThi')},
        ),
    ]
