# Generated by Django 5.2.7 on 2025-10-05 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuocThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10, unique=True)),
                ('tenCuocThi', models.CharField(max_length=200)),
                ('trangThai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiamKhao',
            fields=[
                ('maNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThiSinh',
            fields=[
                ('maNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('chiNhanh', models.CharField(max_length=100)),
                ('vungDonVi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nhom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VongThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenVongThi', models.CharField(max_length=200)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vong_thi', to='core.cuocthi')),
            ],
        ),
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenBaiThi', models.CharField(max_length=200)),
                ('cachChamDiem', models.IntegerField()),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_thi', to='core.vongthi')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuChamDiem',
            fields=[
                ('maPhieu', models.AutoField(primary_key=True, serialize=False)),
                ('maCuocThi', models.CharField(db_index=True, editable=False, max_length=10)),
                ('diem', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baithi')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuocthi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giamkhao')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thisinh')),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vongthi')),
            ],
            options={
                'unique_together': {('thiSinh', 'giamKhao', 'baiThi')},
            },
        ),
    ]
