# Generated by Django 5.2.8 on 2025-11-14 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenBaiThi', models.CharField(max_length=200)),
                ('cachChamDiem', models.IntegerField()),
                ('phuongThucCham', models.CharField(choices=[('TIME', 'Chấm theo thời gian'), ('TEMPLATE', 'Chấm theo mẫu'), ('POINTS', 'Chấm theo thang điểm')], default='POINTS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BanGiamDoc',
            fields=[
                ('maBGD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuocThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10, unique=True)),
                ('tenCuocThi', models.CharField(max_length=200)),
                ('trangThai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiamKhao',
            fields=[
                ('maNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('JUDGE', 'Giám khảo')], db_index=True, default='JUDGE', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThiSinh',
            fields=[
                ('maNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hoTen', models.CharField(max_length=100)),
                ('chiNhanh', models.CharField(max_length=100, null=True)),
                ('vung', models.CharField(blank=True, max_length=100, null=True)),
                ('donVi', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('nhom', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL ảnh (trên Drive) của thí sinh', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaiThiTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='core.baithi')),
            ],
            options={
                'ordering': ['baiThi_id', 'stt'],
            },
        ),
        migrations.CreateModel(
            name='BaiThiTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('content', models.CharField(max_length=500)),
                ('max_score', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.baithitemplatesection')),
            ],
            options={
                'ordering': ['section_id', 'stt'],
            },
        ),
        migrations.CreateModel(
            name='BaiThiTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('score', models.IntegerField()),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='core.baithi')),
            ],
            options={
                'ordering': ['start_seconds', 'end_seconds', 'score'],
            },
        ),
        migrations.CreateModel(
            name='CapThiDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCapDau', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('tenCapDau', models.CharField(blank=True, help_text='Tên hiển thị cặp đấu (nếu muốn đặt). VD: Bảng A - Trận 1', max_length=100, null=True)),
                ('thuTuThiDau', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị cặp đấu')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_pairs', to='core.cuocthi')),
            ],
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='Số sao vote (1–5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True, help_text='Nhận xét của BGD (tuỳ chọn)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giamKhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes', to='core.giamkhao')),
            ],
        ),
        migrations.CreateModel(
            name='ThiSinhCapThiDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Bên trái'), ('R', 'Bên phải')], help_text='L = đội/trận bên trái, R = đội bên phải', max_length=1)),
                ('slot', models.PositiveSmallIntegerField(default=1, help_text='Thứ tự trong đội (dùng cho 2vs2, NvsN)')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.capthidau')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to='core.thisinh')),
            ],
        ),
        migrations.AddField(
            model_name='giamkhao',
            name='contestants_voted',
            field=models.ManyToManyField(blank=True, related_name='judges', through='core.BattleVote', to='core.thisinhcapthidau'),
        ),
        migrations.AddField(
            model_name='battlevote',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.thisinhcapthidau'),
        ),
        migrations.CreateModel(
            name='ThiSinhCuocThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thi_sinh_tham_gia', to='core.cuocthi')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tham_gia', to='core.thisinh')),
            ],
        ),
        migrations.AddField(
            model_name='thisinh',
            name='cuocThi',
            field=models.ManyToManyField(blank=True, related_name='thiSinhs', through='core.ThiSinhCuocThi', to='core.cuocthi'),
        ),
        migrations.CreateModel(
            name='VongThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(editable=False, max_length=10)),
                ('tenVongThi', models.CharField(max_length=200)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vong_thi', to='core.cuocthi')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuChamDiem',
            fields=[
                ('maPhieu', models.AutoField(primary_key=True, serialize=False)),
                ('maCuocThi', models.CharField(db_index=True, editable=False, max_length=10)),
                ('diem', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('thoiGian', models.PositiveIntegerField(default=0, help_text='Thời gian (giây)')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baithi')),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuocthi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giamkhao')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thisinh')),
                ('vongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vongthi')),
            ],
        ),
        migrations.AddField(
            model_name='capthidau',
            name='vongThi',
            field=models.ForeignKey(blank=True, help_text='Có thể gắn với vòng thi (VD: Chung kết, Bán kết...)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_pairs', to='core.vongthi'),
        ),
        migrations.AddField(
            model_name='baithi',
            name='vongThi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_thi', to='core.vongthi'),
        ),
        migrations.CreateModel(
            name='GiamKhaoBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giam_khao_duoc_chi_dinh', to='core.baithi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_cong_bai_thi', to='core.giamkhao')),
            ],
            options={
                'indexes': [models.Index(fields=['giamKhao', 'baiThi'], name='core_giamkh_giamKha_d28f1b_idx')],
                'unique_together': {('giamKhao', 'baiThi')},
            },
        ),
        migrations.AddIndex(
            model_name='thisinhcapthidau',
            index=models.Index(fields=['pair', 'side'], name='core_thisin_pair_id_223f29_idx'),
        ),
        migrations.AddIndex(
            model_name='thisinhcapthidau',
            index=models.Index(fields=['thiSinh'], name='core_thisin_thiSinh_daf032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thisinhcapthidau',
            unique_together={('pair', 'side', 'slot')},
        ),
        migrations.AddIndex(
            model_name='battlevote',
            index=models.Index(fields=['giamKhao', 'entry'], name='core_battle_giamKha_fac5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='battlevote',
            index=models.Index(fields=['entry'], name='core_battle_entry_i_bc4920_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battlevote',
            unique_together={('giamKhao', 'entry')},
        ),
        migrations.AlterUniqueTogether(
            name='thisinhcuocthi',
            unique_together={('thiSinh', 'cuocThi')},
        ),
        migrations.AlterUniqueTogether(
            name='phieuchamdiem',
            unique_together={('thiSinh', 'giamKhao', 'baiThi')},
        ),
    ]
