# Generated by Django 5.2.7 on 2025-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisinh',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
