# Generated by Django 5.2.7 on 2025-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thisinh',
            name='vungDonVi',
        ),
        migrations.AddField(
            model_name='thisinh',
            name='donVi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thisinh',
            name='vung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
