# Generated by Django 5.2.8 on 2025-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battlevote',
            unique_together=set(),
        ),
    ]
