# Generated by Django 5.2.7 on 2025-10-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuchamdiem',
            name='thoiGian',
            field=models.PositiveIntegerField(default=0, help_text='Thời gian (giây)'),
        ),
    ]
