# Generated by Django 5.2.8 on 2025-11-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_battlevote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battlevote',
            unique_together={('giamKhao', 'entry')},
        ),
    ]
