# Generated by Django 5.2.7 on 2025-11-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phieuchamdiem_thoigian'),
    ]

    operations = [
        migrations.AddField(
            model_name='giamkhao',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('JUDGE', 'Giám khảo')], db_index=True, default='JUDGE', max_length=10),
        ),
    ]
