# Generated by Django 5.2.8 on 2025-11-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_battlevote_giamkhao'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Thêm cột giamKhao_id nếu chưa có
            ALTER TABLE core_battlevote
            ADD COLUMN IF NOT EXISTS "giamKhao_id" varchar(20) NULL;

            -- Thêm foreign key sang core_giamkhao(maNV) nếu chưa có
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints
                    WHERE constraint_name = 'core_battlevote_giamKhao_id_fk'
                      AND table_name = 'core_battlevote'
                ) THEN
                    ALTER TABLE core_battlevote
                    ADD CONSTRAINT core_battlevote_giamKhao_id_fk
                    FOREIGN KEY ("giamKhao_id")
                    REFERENCES core_giamkhao ("maNV")
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END$$;
            """,
            reverse_sql="""
            -- Xoá FK nếu tồn tại
            ALTER TABLE core_battlevote
            DROP CONSTRAINT IF EXISTS core_battlevote_giamKhao_id_fk;

            -- Xoá cột nếu tồn tại
            ALTER TABLE core_battlevote
            DROP COLUMN IF EXISTS "giamKhao_id";
            """,
        ),
    ]
