# Generated by Django 5.2.7 on 2025-10-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_thisinh_vungdonvi_thisinh_donvi_thisinh_vung'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithi',
            name='phuongThucCham',
            field=models.CharField(choices=[('TIME', 'Chấm theo thời gian'), ('TEMPLATE', 'Chấm theo mẫu'), ('POINTS', 'Chấm theo thang điểm')], default='POINTS', max_length=20),
        ),
        migrations.CreateModel(
            name='BaiThiTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('score', models.IntegerField()),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='core.baithi')),
            ],
            options={
                'ordering': ['start_seconds', 'end_seconds', 'score'],
            },
        ),
    ]
