# Generated by Django 5.2.7 on 2025-11-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_giamkhao_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiamKhaoBaiThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giam_khao_duoc_chi_dinh', to='core.baithi')),
                ('giamKhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_cong_bai_thi', to='core.giamkhao')),
            ],
            options={
                'indexes': [models.Index(fields=['giamKhao', 'baiThi'], name='core_giamkh_giamKha_d28f1b_idx')],
                'unique_together': {('giamKhao', 'baiThi')},
            },
        ),
    ]
