# Generated by Django 5.2.8 on 2025-11-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_battlevote_giamkhao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='battlevote',
            new_name='core_battle_giam_kh_6990ac_idx',
            old_name='core_battle_giamKha_fac5ec_idx',
        ),
        migrations.AlterField(
            model_name='battlevote',
            name='giamKhao',
            field=models.ForeignKey(blank=True, db_column='giam_khao_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes', to='core.giamkhao'),
        ),
    ]
