# Generated by Django 5.2.7 on 2025-10-15 03:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_baithi_phuongthuccham_baithitimerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisinh',
            name='cuocThi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thi_sinh', to='core.cuocthi'),
        ),
        migrations.AddField(
            model_name='thisinh',
            name='maCuocThi',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phieuchamdiem',
            name='diem',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
