# Generated by Django 5.2.7 on 2025-11-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_giamkhaobaithi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giamkhao',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('JUDGE', 'Giám khảo')], db_index=True, default='JUDGE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thisinh',
            name='chiNhanh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thisinh',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='thisinh',
            name='nhom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
