# Generated by Django 5.2.7 on 2025-10-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_thisinh_cuocthi_thisinh_macuocthi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiThiTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('baiThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='core.baithi')),
            ],
            options={
                'ordering': ['baiThi_id', 'stt'],
            },
        ),
        migrations.CreateModel(
            name='BaiThiTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(default=1)),
                ('content', models.CharField(max_length=500)),
                ('max_score', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.baithitemplatesection')),
            ],
            options={
                'ordering': ['section_id', 'stt'],
            },
        ),
    ]
