# Generated by Django 5.2.7 on 2025-11-13 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_giamkhao_role_alter_thisinh_chinhanh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapThiDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCapDau', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('tenCapDau', models.CharField(blank=True, help_text='Tên hiển thị cặp đấu (nếu muốn đặt). VD: Bảng A - Trận 1', max_length=100, null=True)),
                ('thuTuThiDau', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị cặp đấu')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuocThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_pairs', to='core.cuocthi')),
                ('vongThi', models.ForeignKey(blank=True, help_text='Có thể gắn với vòng thi (VD: Chung kết, Bán kết...)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_pairs', to='core.vongthi')),
            ],
        ),
        migrations.CreateModel(
            name='ThiSinhCapThiDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Bên trái'), ('R', 'Bên phải')], help_text='L = đội/trận bên trái, R = đội bên phải', max_length=1)),
                ('slot', models.PositiveSmallIntegerField(default=1, help_text='Thứ tự trong đội (dùng cho 2vs2, NvsN)')),
                ('image_url', models.URLField(blank=True, help_text='URL ảnh (trên Drive) của thí sinh trong trận này', max_length=500, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.capthidau')),
                ('thiSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to='core.thisinh')),
            ],
            options={
                'indexes': [models.Index(fields=['pair', 'side'], name='core_thisin_pair_id_223f29_idx'), models.Index(fields=['thiSinh'], name='core_thisin_thiSinh_daf032_idx')],
                'unique_together': {('pair', 'side', 'slot')},
            },
        ),
    ]
