# Generated by Django 5.1.14 on 2025-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_giamkhao_role_alter_thisinh_chinhanh_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanGiamDoc",
            fields=[
                (
                    "maBGD",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("ten", models.CharField(max_length=255)),
                ("token", models.CharField(editable=False, max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
