# Generated by Django 5.1.14 on 2025-11-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bangiamdoc"),
        ("core", "0006_capthidau_thisinhcapthidau"),
    ]

    operations = []
